#!/usr/bin/python

from __future__ import division

import argparse

from digikey import robot
import digikey

parser = argparse.ArgumentParser()

parser.add_argument('resistance', metavar='RESISTANCE', type=str, help='resistance (example: 10k)')
parser.add_argument('--error', metavar='ERROR', type=float, help='maximum error from desired resistance in percent (default: 1)', default=1)
parser.add_argument('--tolerance', metavar='TOLERANCE', type=float, help='maximum tolerance (default: 5)', default=5)
parser.add_argument('--package', metavar='PACKAGE', type=str, help='package / case (default: 0603) (use ANY for any)', default='0603')

args = parser.parse_args()


r = robot.Robot.start('http://www.digikey.com/product-search/en/resistors/chip-resistor-surface-mount')
fp = digikey.FilteringPage(r)

#print r.html


options = []
options.append(('quantity', 10))
options.append(('stock', 1))
options.append(('ColumnSort', 1000011)) # XXX does this change?
options.extend(fp.produce_filter_options('Resistance (Ohms)',
    lambda s: digikey.within_tolerance(digikey.parse_number(args.resistance), args.error, digikey.parse_number(s))))
options.extend(fp.produce_filter_options('Package / Case',
    lambda s: s.strip().startswith(args.package) or args.package == 'ANY'))
def meets_tolerance((sup, inf)):
    return sup >= 1-args.tolerance/100 and inf <= 1+args.tolerance/100
options.extend(fp.produce_filter_options('Tolerance',
    lambda s: meets_tolerance(digikey.parse_tolerance(s))))

url = r.get_new_url(options=options)
print url

r2 = robot.Robot.start(url)
rp = digikey.FilteringPage(r2)
print rp.first_part_number
